### ISSUE TITLE
US#3: Logout

### ISSUE THREAD

**Issue by sFranchetto** [jonathan-githubofficial/awaazo#11]
**Priority:**  P2

**Story Points:**  3

**User Story:**  
As a logged in User,
I would like to Logout,
So that my session is terminated and my personal information remains secure.

**Potential Risks:**  
- Loss of unsaved Data 
- Inadequate security (Session hijacking, unauthorized logouts)
- Forgotten passwords

**Demo Steps:**  
1. User must be logged in firstly to be able to log out.
2. Upon clicking his/her avatar, the last option in the drop-down menu will be a "Log out" button.
3. Users clicks log out button, a confirmation window pops up ensuring it wasn't an accidental click.
4. User confirms the Log out is genuine and page is refreshed to the home page.

**Acceptance Criteria:**  
1. User clicks "Log out" button on the drop down, confirms the logout and is redirected to home page
   - Sub-criteria 1.1: Session is terminated
   - Sub-criteria 1.2: User remains logged out while navigating the website.
3. User clicks "Log out" button on the drop down, and clicks cancel on the pop-up window. 
   - Sub-criteria 2.1: User keeps his/her session.

**Sub Tasks**
[#62](https://github.com/jonathan-githubofficial/awaazo/issues/62) 
[#63](https://github.com/jonathan-githubofficial/awaazo/issues/63)

**Comment by jonathan-githubofficial** [comment]
Project Progress video : https://youtu.be/g0pme7nBDzI

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/db674005-d1f4-482c-9925-8814373804eb

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/175e5716-8a8e-4db7-af13-7063661c8560

Commit where this was done: https://github.com/awaazo/awaazo/commit/0cd3f5ed12371c6606c69f35b7aa836dfab79b7e

**Comment by Radwanbaba13** [comment]
Radwan[frontend]: User logout functionality demo

https://github.com/awaazo/awaazo/assets/68618601/dfb8c095-0082-4046-9d9d-fdbf1d1d5dc7

**Comment by soni2261** [comment]
Sonia[frontend]: Logout Item in Navbar - Code Overview
video link:
https://clipchamp.com/watch/0LN2KWJQ369
