### ISSUE TITLE
US#1: User account creation

### ISSUE THREAD

**Issue by sFranchetto** [jonathan-githubofficial/awaazo#2]
**Priority**: P1
**Story Points**: 8

**User Story:**
As a potential user, 
I want to create a personal account ,
So that I can access podcasts, save my preferences, and engage with the community.

**Potential risks:**
- Security (password not strong enough)
- Scalability
- User experience (Technical errors, lengthy registration process)

**Demo steps:**
1. Upon landing on the homepage, I should see a "Register" button that would redirect me to the registration page.
2. On the registration page, I should find the form to create an account with the following fields: Username, Email, Password, Confirm Password.
3. I may also choose to sign up with Google/Facebook.
4. Upon completing the form with the properly inputted fields and having passwords match, I will be given feedback if there are any errors.
5. If all is well, I should be redirected to a Profile setup page where I can complete my profile.

**Acceptance Criteria:**
1. A user registers with with appropriate inputs in the form fields
-Sub-criteria 1.1: User passwords are hashed and stored.
-Sub-criteria 1.2:Account information is created & stored in database without any errors.
-Sub-criteria 1.3: Account creation should pass tests.

2. A user registers with with inappropriate inputs in the form fields
-Sub-criteria 2.1: The register page refreshes and gives feedback on fault inputs

**Sub Tasks:**
#35 
#36 
#37

**Comment by jonathan-githubofficial** [comment]
backend was addressed ticket : #14

**Comment by sFranchetto** [comment]
All subtasks complete, ready for stakeholder signoff

**Comment by jonathan-githubofficial** [comment]
Project Progress video : https://youtu.be/g0pme7nBDzI

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/ba60ef31-fe9d-44d7-9dbe-7f2785a11104

Commit where this was done: https://github.com/awaazo/awaazo/commit/0cd3f5ed12371c6606c69f35b7aa836dfab79b7e

**Comment by mathieutrudeau** [comment]
![image](https://github.com/awaazo/awaazo/assets/46968018/7dbde54d-e3af-4589-8503-6784e3d9105e)

**Comment by mathieutrudeau** [comment]
So far, SSO has only been implemented with Google. Other providers might be added in the future in order to improve usability for the users.

**Comment by mathieutrudeau** [comment]
[Lighthouse usability report for the register page](https://github.com/awaazo/awaazo/files/13369338/download.pdf)
