### ISSUE TITLE
DEV #1 : Setup ASP.NET environment

### ISSUE THREAD

**Issue by mubashir494** [jonathan-githubofficial/awaazo#28]
**Priority:**  P1

**Story Points:**  3

**Developer Story:**  
As a developer, I need to set up my development environment to facilitate coding, testing, and debugging tasks efficiently.

**Potential Risks:**  
- Delay in setup can cause overall project to be slower

**Acceptance Criteria:**  
1. A running boiler plate code

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/f89c52de-b7e8-4fb8-8de4-27676145e561
