### ISSUE TITLE
DEV #2: Setup Next JS project

### ISSUE THREAD

**Issue by mubashir494** [jonathan-githubofficial/awaazo#29]
**Priority:**  P2

**Story Points:**  2

**User Story:**  
As a developer, I  need to set up my development environment to facilitate coding, testing, and debugging tasks efficiently. 

**Potential Risks:**  
- Delay in setup can cause overall project to be delayed

**Acceptance Criteria:**  
1.A running boiler plate code

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/1106ee8b-8025-482d-84e1-98ebb098d1fa

**Comment by jonathan-githubofficial** [comment]
[issue-29.webm](https://github.com/awaazo/awaazo/assets/106629548/86c4a291-e5d1-4863-8275-47330d9f3871)
