### ISSUE TITLE
DEV #3 : Setup Docker for the project

### ISSUE THREAD

**Issue by mubashir494** [jonathan-githubofficial/awaazo#30]
**Priority:**  P1

**Story Points:**  5

**User Story:**  
As a developer, I want to setup docker so that I can containerize the application and its dependencies, ensuring consistency and ease of deployment across various environments.

**Potential Risks:**  
- Misconfigurations can lead to connectivity issues and security risks

**Demo Steps:**  
1. Run "docker compose up" in root directory to run all the associated containers

**Acceptance Criteria:**  
1. Docker compose up run all the associated container

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/2d21a006-fa28-4d0f-8dd3-8a6855c5c702
