### ISSUE TITLE
DEV #4 :Implement CI pipeline for the Project

### ISSUE THREAD

**Issue by mubashir494** [jonathan-githubofficial/awaazo#31]
**Priority:**  P1

**Story Points:**  4

**User Story:**  
As a developer, I want to have a fully functional CI pipeline for Project, so that I can automate the build, test, and deployment processes, ensuring that code changes are continuously integrated and validated.

**Potential Risks:**  
- The process of implementing CI can be complex and time consuming

**Demo Steps:**  
1. Commit the changes to the main branch in github

**Acceptance Criteria:**  
1. On commit, it gives detail about the build
   - Sub-criteria 1.1: If it fails then code is not merged
   - Sub-criteria 1.2: If it passes then code is tested
2. On testing, it provides detail about the testing
   - Sub-criteria 2.1: If tesing fail then code is not merged
   - Sub-criteria 2.2: If test passes then it checks whether the coverage is greater then 80% if yes then the code is merged, if not then the merge is blocked
3. All the processes are repeated for both the frontend and backend

**Comment by mathieutrudeau** [comment]
https://github.com/awaazo/awaazo/assets/46968018/547a641a-b3a6-435e-a0ab-8572c33fae29

**Comment by mathieutrudeau** [comment]
![image](https://github.com/awaazo/awaazo/assets/46968018/2a3cabd2-30d6-41ba-9b2b-27d45158ed5c)

**Comment by mathieutrudeau** [comment]
The Tests are triggered every time a PR is made. They're also triggered whenever the main codebase is changed.
