### ISSUE TITLE
US#2: User log in

### ISSUE THREAD

**Issue by sFranchetto** [jonathan-githubofficial/awaazo#6]
**Priority** : P1
**Story Points:**  8

**User Story:**  
As a registered user,
I want to be able to log in to my account,
So that I can access my personalized content and settings.

**Potential risks:**
- Security (user cannot log in due to being hacked)
- Account lock (user entering wrong info too many time will cause them to be locked out for 5 minutes)
- Session management (Ensure the backend handles sessions well)

**Demo steps:**
1. Upon landing on the homepage, I should see a "Log In" button that would redirect me to the login page.
2. On the login page, I should find a form where I can input my username OR email AND my password.
3. Given that I already created an account, upon completing the form and clicking "Log in" I will be redirected to my homepage if and only if the username/email and password match with what is stored in the database.
4. If the username/email and password do not match a record in the database, I will be given feedback of my faulty inputs.

**Acceptance Criteria:**
1. A user logs in with appropriate credentials
-Sub-criteria 1.1: User gets redirected to his/her homepage
-Sub-criteria 1.2: A session token is created
2. A user attempts to log in with invalid credentials
-Sub-criteria 2.1: The login page refreshes and gives feedback on the faulty inputs

**Sub Tasks:**
#35 
#36 
#37

**Comment by jonathan-githubofficial** [comment]
backend was addressed ticket : #14

**Comment by sFranchetto** [comment]
All subtasks complete, ready for stakeholder signoff

**Comment by jonathan-githubofficial** [comment]
Project Progress video : https://youtu.be/g0pme7nBDzI

**Comment by sFranchetto** [comment]
https://github.com/awaazo/awaazo/assets/31280516/73dea7dc-c20b-4757-9bf1-b120c3ec8578

Commit where this was done: https://github.com/awaazo/awaazo/commit/0cd3f5ed12371c6606c69f35b7aa836dfab79b7e

**Comment by mathieutrudeau** [comment]
![image](https://github.com/awaazo/awaazo/assets/46968018/765ad27e-14ae-48a6-b240-e9e1998e5632)
